id: I22634142
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T08:00:20+00:00'
last_modified: '2022-06-15T15:21:09.797774+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22323
  title: ཡིག་དྲུག་གི་འཁོར་ལོའི་ཁུངས་དང་བསྐོར་ཚུལ་གྱི་གནད་དམིགས་པ་བྱ་ཚུལ་ཕན་ཡོན་དང་བཅས་པ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5AF2:
      image_group_id: I1PD36249
      title: Volume 1 of bcom ldan 'das dpal rnam par snang mdzad kyi bum chog
      total_pages: 42
      order: 1
      base_file: 5AF2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
